// <auto-generated />
using System;
using Deckle.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deckle.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131204236_RefactorDataSourcePolymorphic")]
    partial class RefactorDataSourcePolymorphic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deckle.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Components");

                    b.HasDiscriminator<string>("ComponentType").HasValue("Component");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Deckle.Domain.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DataSources");

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Deckle.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DirectoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Tags"), new[] { "jsonb_path_ops" });

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ProjectId", "Path")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.HasIndex("Status", "UploadedAt");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.FileDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentDirectoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ParentDirectoryId", "Name")
                        .IsUnique();

                    b.ToTable("FileDirectories");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Projects", t =>
                        {
                            t.HasCheckConstraint("CK_Projects_Code_Format", "\"Code\" ~ '^[a-zA-Z0-9-]+$'");
                        });
                });

            modelBuilder.Entity("Deckle.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User");

                    b.Property<int>("StorageQuotaMb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<long>("StorageUsedBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.UserProject", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Card", b =>
                {
                    b.HasBaseType("Deckle.Domain.Entities.Component");

                    b.Property<string>("BackDesign")
                        .HasColumnType("text");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FrontDesign")
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("jsonb");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DataSourceId");

                    b.HasDiscriminator().HasValue("Card");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Dice", b =>
                {
                    b.HasBaseType("Deckle.Domain.Entities.Component");

                    b.Property<string>("BaseColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Dice");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.PlayerMat", b =>
                {
                    b.HasBaseType("Deckle.Domain.Entities.Component");

                    b.Property<string>("BackDesign")
                        .HasColumnType("text");

                    b.Property<decimal?>("CustomHeightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CustomWidthMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FrontDesign")
                        .HasColumnType("text");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresetSize")
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("jsonb");

                    b.HasIndex("DataSourceId");

                    b.ToTable("Components", t =>
                        {
                            t.Property("BackDesign")
                                .HasColumnName("PlayerMat_BackDesign");

                            t.Property("DataSourceId")
                                .HasColumnName("PlayerMat_DataSourceId");

                            t.Property("FrontDesign")
                                .HasColumnName("PlayerMat_FrontDesign");
                        });

                    b.HasDiscriminator().HasValue("PlayerMat");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.GoogleSheetsDataSource", b =>
                {
                    b.HasBaseType("Deckle.Domain.Entities.DataSource");

                    b.Property<string>("CsvExportUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GoogleSheetsId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleSheetsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SheetGid")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("GoogleSheets");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.SampleDataSource", b =>
                {
                    b.HasBaseType("Deckle.Domain.Entities.DataSource");

                    b.Property<string>("JsonData")
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("Sample");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Component", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.DataSource", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.Project", "Project")
                        .WithMany("DataSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.File", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.FileDirectory", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Deckle.Domain.Entities.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deckle.Domain.Entities.User", "UploadedBy")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Project");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.FileDirectory", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.FileDirectory", "ParentDirectory")
                        .WithMany("ChildDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Deckle.Domain.Entities.Project", "Project")
                        .WithMany("FileDirectories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDirectory");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.UserProject", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deckle.Domain.Entities.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Card", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.PlayerMat", b =>
                {
                    b.HasOne("Deckle.Domain.Entities.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.FileDirectory", b =>
                {
                    b.Navigation("ChildDirectories");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.Project", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("DataSources");

                    b.Navigation("FileDirectories");

                    b.Navigation("Files");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("Deckle.Domain.Entities.User", b =>
                {
                    b.Navigation("UploadedFiles");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
